export default {
    darkMode: 'class',
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}"
    ],
    theme: {
        extend: {
            fontFamily: {
                sans: ['Poppins', 'sans-serif'],
            },
            colors: {
                brand: {
                    navy: {
                        DEFAULT: '#0B1F4D',
                        50: '#EEF2FA',
                        100: '#D9E2F3',
                        200: '#AEC0E4',
                        300: '#7F98D0',
                        400: '#4C6BB5',
                        500: '#2A4791',
                        600: '#1A2F6E',
                        700: '#0B1F4D',
                        800: '#081736',
                        900: '#050E24',
                    },
                    emerald: {
                        DEFAULT: '#18C37E',
                        50: '#EAFBF4',
                        100: '#CFF6E5',
                        200: '#A0EDCD',
                        300: '#66E1B0',
                        400: '#3AD499',
                        500: '#18C37E',
                        600: '#0FA066',
                        700: '#0D8153',
                        800: '#0C6945',
                        900: '#0A5539',
                    },
                    mint: '#EAFBF4',
                },
                surface: 'rgb(var(--surface) / <alpha-value>)',
            },
            backgroundColor: {
                surface: 'rgb(var(--surface) / <alpha-value>)',
                slate: {
                    50: 'rgb(var(--bg-slate-50) / <alpha-value>)',
                    100: 'rgb(var(--bg-slate-100) / <alpha-value>)',
                    200: 'rgb(var(--bg-slate-200) / <alpha-value>)',
                    300: 'rgb(var(--bg-slate-300) / <alpha-value>)',
                    400: 'rgb(var(--bg-slate-400) / <alpha-value>)',
                    500: 'rgb(var(--bg-slate-500) / <alpha-value>)',
                    600: 'rgb(var(--bg-slate-600) / <alpha-value>)',
                    700: 'rgb(var(--bg-slate-700) / <alpha-value>)',
                    800: 'rgb(var(--bg-slate-800) / <alpha-value>)',
                    900: 'rgb(var(--bg-slate-900) / <alpha-value>)',
                    950: '#020617',
                },
                brand: {
                    mint: 'rgb(var(--brand-mint) / <alpha-value>)',
                },
            },
            textColor: {
                slate: {
                    50: '#ffffff',
                    100: 'rgb(var(--text-slate-100) / <alpha-value>)',
                    200: 'rgb(var(--text-slate-200) / <alpha-value>)',
                    300: 'rgb(var(--text-slate-300) / <alpha-value>)',
                    400: 'rgb(var(--text-slate-400) / <alpha-value>)',
                    500: 'rgb(var(--text-slate-500) / <alpha-value>)',
                    600: 'rgb(var(--text-slate-600) / <alpha-value>)',
                    700: 'rgb(var(--text-slate-700) / <alpha-value>)',
                    800: 'rgb(var(--text-slate-800) / <alpha-value>)',
                    900: 'rgb(var(--text-slate-900) / <alpha-value>)',
                    950: 'rgb(var(--text-slate-950) / <alpha-value>)',
                },
                gray: {
                    50: '#ffffff',
                    100: 'rgb(var(--text-slate-100) / <alpha-value>)',
                    200: 'rgb(var(--text-slate-200) / <alpha-value>)',
                    300: 'rgb(var(--text-slate-300) / <alpha-value>)',
                    400: 'rgb(var(--text-slate-400) / <alpha-value>)',
                    500: 'rgb(var(--text-slate-500) / <alpha-value>)',
                    600: 'rgb(var(--text-slate-600) / <alpha-value>)',
                    700: 'rgb(var(--text-slate-700) / <alpha-value>)',
                    800: 'rgb(var(--text-slate-800) / <alpha-value>)',
                    900: 'rgb(var(--text-slate-900) / <alpha-value>)',
                    950: 'rgb(var(--text-slate-950) / <alpha-value>)',
                },
                brand: {
                    navy: {
                        DEFAULT: 'rgb(var(--text-brand-navy) / <alpha-value>)',
                    },
                },
            },
            borderColor: {
                slate: {
                    50: 'rgb(var(--border-slate-50) / <alpha-value>)',
                    100: 'rgb(var(--border-slate-100) / <alpha-value>)',
                    200: 'rgb(var(--border-slate-200) / <alpha-value>)',
                    300: 'rgb(var(--border-slate-300) / <alpha-value>)',
                    400: 'rgb(var(--border-slate-400) / <alpha-value>)',
                    500: 'rgb(var(--border-slate-500) / <alpha-value>)',
                    600: 'rgb(var(--border-slate-600) / <alpha-value>)',
                    700: 'rgb(var(--border-slate-700) / <alpha-value>)',
                    800: '#1e293b',
                    900: '#0f172a',
                },
                gray: {
                    50: 'rgb(var(--border-slate-50) / <alpha-value>)',
                    100: 'rgb(var(--border-slate-100) / <alpha-value>)',
                    200: 'rgb(var(--border-slate-200) / <alpha-value>)',
                    300: 'rgb(var(--border-slate-300) / <alpha-value>)',
                    400: 'rgb(var(--border-slate-400) / <alpha-value>)',
                    500: 'rgb(var(--border-slate-500) / <alpha-value>)',
                    600: 'rgb(var(--border-slate-600) / <alpha-value>)',
                    700: 'rgb(var(--border-slate-700) / <alpha-value>)',
                },
            },
            divideColor: {
                slate: {
                    50: 'rgb(var(--border-slate-50) / <alpha-value>)',
                    100: 'rgb(var(--border-slate-100) / <alpha-value>)',
                    200: 'rgb(var(--border-slate-200) / <alpha-value>)',
                    300: 'rgb(var(--border-slate-300) / <alpha-value>)',
                    400: 'rgb(var(--border-slate-400) / <alpha-value>)',
                    500: 'rgb(var(--border-slate-500) / <alpha-value>)',
                    600: 'rgb(var(--border-slate-600) / <alpha-value>)',
                    700: 'rgb(var(--border-slate-700) / <alpha-value>)',
                },
            },
            placeholderColor: {
                slate: {
                    50: '#ffffff',
                    100: 'rgb(var(--text-slate-100) / <alpha-value>)',
                    200: 'rgb(var(--text-slate-200) / <alpha-value>)',
                    300: 'rgb(var(--text-slate-300) / <alpha-value>)',
                    400: 'rgb(var(--text-slate-400) / <alpha-value>)',
                    500: 'rgb(var(--text-slate-500) / <alpha-value>)',
                    600: 'rgb(var(--text-slate-600) / <alpha-value>)',
                    700: 'rgb(var(--text-slate-700) / <alpha-value>)',
                    800: 'rgb(var(--text-slate-800) / <alpha-value>)',
                    900: 'rgb(var(--text-slate-900) / <alpha-value>)',
                },
            },
            boxShadow: {
                card: '0 1px 3px rgba(11, 31, 77, 0.06), 0 8px 24px rgba(11, 31, 77, 0.05)',
                'card-hover': '0 2px 6px rgba(11, 31, 77, 0.08), 0 16px 40px rgba(11, 31, 77, 0.10)',
                btn: '0 4px 12px rgba(24, 195, 126, 0.25)',
                'btn-navy': '0 4px 12px rgba(11, 31, 77, 0.25)',
            },
            borderRadius: {
                '4xl': '2rem',
            },
        },
    },
    plugins: [],
}
